name: Deploy to Dev environment

on:
  push:
    branch:
      - main
  workflow_dispatch:

jobs:
  Release-GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/twohoursonelife/junior
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ghcr.io/twohoursonelife/junior:latest
          labels: ${{ steps.meta.outputs.labels }}

  Deploy-Development:
    needs:
      - Release-GHCR
      - Deploy-DEV-Commands
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy via webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEV_DEPLOY_WEBHOOK_URL }}

  Deploy-DEV-Commands:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy commands
        run: node deploy-commands.js
        env:
          DEV_TOKEN: ${{ secrets.DEV_BOT_TOKEN }}
          CLIENTID: ${{ secrets.DEV_CLIENT_ID }}
          GUILDID: ${{ secrets.DEV_GUILD_ID }}
