name: Release Junior

on:
  release:
    types:
      - created

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/twohoursonelife/junior
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add version.txt
        run: git describe --tags --abbrev=0 > version.txt

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: . # Intentionally using Path context to include version.txt
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ghcr.io/twohoursonelife/junior:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-commands:
    runs-on: ubuntu-latest
    environment: prod-commands
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Deploy commands
        run: node deploy-commands.js
        env:
          PROD_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
